# Generated by Django 4.0.3 on 2022-06-06 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('building', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingradient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pizza_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='pizza_images')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_store.clientprofile')),
                ('ingradients', models.ManyToManyField(related_name='pizza_example_ingradient', to='pizza_store.ingradient')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='pizza_example_tag', to='pizza_store.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(auto_created=True, default=False)),
                ('accepted', models.BooleanField(auto_created=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('done_at_at', models.DateTimeField(blank=True, null=True)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_store.adress')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_store.clientprofile')),
            ],
        ),
        migrations.AddField(
            model_name='adress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_store.clientprofile'),
        ),
    ]
