# Generated by Django 4.0.3 on 2022-06-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='pizza_store.tag'),
        ),
    ]
