# Generated by Django 4.0.3 on 2022-06-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0006_alter_pizza_ingradients_alter_pizza_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingradient',
            name='price',
            field=models.IntegerField(default=3, null=True),
        ),
    ]
