# Generated by Django 4.0.3 on 2022-06-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0007_alter_ingradient_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='tags',
        ),
        migrations.AlterField(
            model_name='adress',
            name='building',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='adress',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
