# Generated by Django 4.0.3 on 2022-06-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0008_remove_pizza_description_remove_pizza_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ready_time',
            field=models.IntegerField(default=40, null=True),
        ),
    ]
