# Generated by Django 4.0.3 on 2022-07-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0012_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza_Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=1)),
                ('pizza', models.ManyToManyField(to='pizza_store.pizza')),
            ],
        ),
    ]
