# Generated by Django 4.0.3 on 2022-07-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0013_pizza_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_list',
            field=models.ManyToManyField(blank=True, to='pizza_store.pizza_size'),
        ),
    ]
