# Generated by Django 4.0.3 on 2022-07-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0015_alter_order_order_list_delete_pizza_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=1)),
                ('pizza', models.ManyToManyField(to='pizza_store.pizza')),
            ],
        ),
    ]
