# Generated by Django 4.0.3 on 2022-07-12 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0017_alter_order_order_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='pizza',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_store.pizza'),
            preserve_default=False,
        ),
    ]
