# Generated by Django 4.0.3 on 2022-07-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0019_alter_order_customer_address_alter_order_adress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
    ]
