# Generated by Django 4.0.3 on 2022-07-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0020_rename_adress_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
