# Generated by Django 4.0.3 on 2022-08-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0022_order_email_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='done',
        ),
        migrations.RemoveField(
            model_name='order',
            name='done_at',
        ),
    ]
