# Generated by Django 4.0.3 on 2022-08-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0023_remove_order_accepted_at_remove_order_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accepted',
        ),
    ]
